### ISSUE TITLE
Changing order of budget categories by drag and drop seems to be broken with 23.7.0

### ISSUE THREAD

**Issue by marijnkieboom** [actualbudget/actual-server#223]
I have seen the warning on the release notes that here are several bugs already found on 23.7.0, feel free to delete this issue if a fix is already on its way or something.

But I used to be able to change the order of budget categories by dragging them to their new place, and this doesn't seem to be working anymore with the new version.

**Comment by MatissJanis** [comment]
Fixed here: https://github.com/actualbudget/actual/pull/1289

Will be released in v23.7.1

**Comment by qu4cks4lb3r** [comment]
Hi,

I just started using Actual Budget today and stumbled upon this bug report as I'm experiencing the same issue. I'm on Version v23.7.1. 

So it seems this issue is not resolved.

**Comment by MatissJanis** [comment]
Thanks. We spotted some more issues with it. The revert back to the original implementation will be soon available in v23.7.2

Here's the revert: https://github.com/actualbudget/actual/pull/1306
